x = int(input('x: '))
opr = input('Operator: ')
y = int(input('y: '))
if opr == '+' : print(x+y)
elif opr == '-' : print(x-y)
elif opr == '*' : print(x*y)
elif opr == '/' : print('{:.2f}'.format(x/y))
elif opr == '%' : print(x%y)
else : print('Unknown Operator')